version: '3'

services:
  yarn:
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  ui:
    image: node:alpine
    working_dir: /workspace/packages/ui
    volumes:
      - ./:/workspace
    entrypoint: yarn docs:server
    environment:
      - PORT=8012
    ports:
      - 8012:8012
