version: '3'

services:
  yarn:
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  ui:
    image: node:alpine
    working_dir: /workspace/packages/ui
    volumes:
      - ./:/workspace
    entrypoint: yarn docs:server
    environment:
      - PORT=8002
    ports:
      - 8002:8002

  dashboard:
    image: node:alpine
    working_dir: /workspace/packages/dashboard
    volumes:
      - ./:/workspace
    entrypoint: yarn dev
    environment:
      - PORT=8000
    ports:
      - 8000:8000
